//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\doc\SCIENCE\TJC_analysis\codeCAE\dialog_thread.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: rusla
//              Version: NX 1919
//              Date: 12-07-2022  (Format: mm-dd-yyyy)
//              Time: 23:43
//
//==============================================================================

#ifndef DIALOG_THREAD_H_INCLUDED
#define DIALOG_THREAD_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_DrawingArea.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>
#include <NXOpen/BlockStyler_Button.hxx>

//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport dialog_thread
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    dialog_thread();
    ~dialog_thread();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the dialog_thread.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::DrawingArea* drawingArea0;// Block type: Drawing Area
    NXOpen::BlockStyler::DoubleBlock* double_d3;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double_ln;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double_phi;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double_lm;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double_l1;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double_d4;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double_d5;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double_16;// Block type: Double
    NXOpen::BlockStyler::Group* group1;// Block type: Group
    NXOpen::BlockStyler::DrawingArea* drawingArea01;// Block type: Drawing Area
    NXOpen::BlockStyler::DoubleBlock* double_h1;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double_f1;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double_h;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double_P;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double_f;// Block type: Double
    NXOpen::BlockStyler::Button* button0;// Block type: Button
    NXOpen::BlockStyler::Group* group2;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* double_meshSize;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double_innerGrad;// Block type: Double
    NXOpen::BlockStyler::Group* group3;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* double0;// Block type: Double
    NXOpen::BlockStyler::Button* button01;// Block type: Button
    NXOpen::BlockStyler::Button* button02;// Block type: Button
    
};
#endif //DIALOG_THREAD_H_INCLUDED
